name: Aviso Discord

on:
  schedule:
    - cron: "17 15 * * 3"
    - cron: "22 15 * * 3"
    - cron: "27 15 * * 3"
    - cron: "32 15 * * 3"

    - cron: "17 16 * * 3"
    - cron: "22 16 * * 3"
    - cron: "27 16 * * 3"
    - cron: "32 16 * * 3"

    - cron: "17 17 * * 3"
    - cron: "22 17 * * 3"
    - cron: "27 17 * * 3"
    - cron: "32 17 * * 3"

    - cron: "17 18 * * 3"
    - cron: "22 18 * * 3"
    - cron: "27 18 * * 3"
    - cron: "32 18 * * 3"

    - cron: "17 19 * * 3"
    - cron: "22 19 * * 3"
    - cron: "27 19 * * 3"
    - cron: "32 19 * * 3"

  workflow_dispatch:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -i -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "@everyone tenemos raid hoy a las 21:30",
                 "allowed_mentions": { "parse": ["everyone"] }
               }' \
               "$DISCORD_WEBHOOK_URL"
