name: Aviso Discord

on:
  schedule:
    - cron: "16 15 * * 3"
    - cron: "17 15 * * 3"
    - cron: "18 15 * * 3"
    - cron: "19 15 * * 3"
    - cron: "21 15 * * 3"
    - cron: "22 15 * * 3"

    - cron: "16 16 * * 3"
    - cron: "17 16 * * 3"
    - cron: "18 16 * * 3"
    - cron: "19 16 * * 3"
    - cron: "21 16 * * 3"
    - cron: "22 16 * * 3"

    - cron: "16 17 * * 3"
    - cron: "17 17 * * 3"
    - cron: "18 17 * * 3"
    - cron: "19 17 * * 3"
    - cron: "21 17 * * 3"
    - cron: "22 17 * * 3"

    - cron: "25 14 * * 3"
    - cron: "25 15 * * 3"
    - cron: "25 16 * * 3"
    - cron: "25 17 * * 3"
    - cron: "25 18 * * 3"
    - cron: "25 19 * * 3"

  workflow_dispatch:

jobs:
  send-discord-message:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -i -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "@everyone tenemos raid hoy a las 21:30",
                 "allowed_mentions": { "parse": ["everyone"] }
               }' \
               "$DISCORD_WEBHOOK_URL"
